export interface CasteData {
  categories: string[];
  subCastes: Record<string, string[]>;
}

export const AP_CASTES: CasteData = {
  categories: [
    'OC',
    'BC-A',
    'BC-B',
    'BC-C',
    'BC-D',
    'BC-E',
    'SC',
    'ST',
    'Other'
  ],
  subCastes: {
    'OC': [
      'Brahmin',
      'Reddy',
      'Kamma',
      'Kapu / Telaga / Balija / Ontari',
      'Arya Vysya / Komati',
      'Kalinga Vysya',
      'Kshatriya / Raju',
      'Velama (Padmanayaka)',
      'Nagaralu',
      'Marwari / Jain',
      'Sindhi / Punjabi',
      'Other Sub-Caste'
    ],
    'BC-A': [
      'Agnikula Kshatriya / Palli / Vadabalija / Bestha / Jalari / Gangaputra',
      'Nayee Brahmin / Mangali / Bajantri',
      'Rajaka / Chakali / Dhobi',
      'Vamsharaj / Pitchiguntla',
      'Kalinga / Buragam Kalinga',
      'Kandra',
      'Medari / Mahendra',
      'Odde / Vaddi / Vaddera',
      'Valmiki (Plain)',
      'Dasari (Plain)',
      'Gudala',
      'Veeramushti / Nettikotala',
      'Jogi',
      'Mondi Banda / Mondi Varu',
      'Dommara',
      'Gangireddu / Poosala',
      'Katipapala',
      'Koracha',
      'Pamula',
      'Budabukkala',
      'Other Sub-Caste'
    ],
    'BC-B': [
      'Padmashali / Sali / Senapathulu',
      'Devanga',
      'Kuruba / Kuruma',
      'Ediga / Gouda / Srisayana / Settibalija / Yata',
      'Jangam',
      'Viswabrahmin / Ausula / Kamsali / Kammari / Vadrangi / Silpi',
      'Kummari / Kulala / Salivahana',
      'Swakula Sali',
      'Neeli',
      'Patkar',
      'Togata / Togataveera Kshatriya',
      'Perika / Perika Balija',
      'Nessi / Kurni',
      'Atagara',
      'Khatri',
      'Other Sub-Caste'
    ],
    'BC-C': [
      'Scheduled Caste Converts to Christianity',
      'Other Sub-Caste'
    ],
    'BC-D': [
      'Turpu Kapu (Gajula Kapu)',
      'Kalinga (BC-D)',
      'Koppula Velama',
      'Polinati Velama',
      'Yadava / Golla',
      'Pondara',
      'Gavara',
      'Sondi / Sundhi',
      'Nagavamsam / Nagavaddilu',
      'Kurakula',
      'Mudiraj / Mutrasi / Tenugollu',
      'Bhatraju',
      'Rongali',
      'Ayyaraka',
      'Kasi Kapu',
      'Mathura',
      'Sadhu Chetty',
      'Uppara / Sagara',
      'Vanjara',
      'Other Sub-Caste'
    ],
    'BC-E': [
      'Dudekula / Laddaf / Pinjari / Noor Basha',
      'Mehtar (Muslim)',
      'Shaik / Sheikh',
      'Syed (Backward)',
      'Attar Saibulu / Gandhallu',
      'Dhobi Muslim / Muslim Rajaka',
      'Faqir / Fakir Budbudki',
      'Garadi',
      'Gosangi Muslim',
      'Guddi Eluguvallu',
      'Kankali',
      'Labbi',
      'Pakeerla',
      'Borewale',
      'Other Sub-Caste'
    ],
    'SC': [
      'Madiga',
      'Mala',
      'Relli',
      'Adi Andhra',
      'Adi Dravida',
      'Arundhatiya',
      'Bariki',
      'Bavuri',
      'Chachati',
      'Dandasi',
      'Dom / Domb / Dombara / Paidi',
      'Ghasi / Haddi',
      'Godagali',
      'Jaggali',
      'Jambuvulu',
      'Mala Dasari',
      'Mala Jangam',
      'Mala Sale (Netkani)',
      'Paky / Moti / Thoti',
      'Pamidi',
      'Panchama',
      'Pano',
      'Samagara',
      'Samban',
      'Sapru',
      'Other Sub-Caste'
    ],
    'ST': [
      'Savara',
      'Jatapu',
      'Konda Dhora',
      'Gadaba',
      'Bagata',
      'Chenchu',
      'Gond / Naikpod / Rajgond',
      'Goudu',
      'Kammara',
      'Kattunayakan',
      'Konda Kapu',
      'Konda Reddi',
      'Kondh / Kuvi',
      'Kotia',
      'Koya / Doli Koya / Gutta Koya',
      'Kulia',
      'Malis',
      'Manna Dhora',
      'Mukha Dhora',
      'Porja',
      'Reddi Dhora',
      'Rona / Rena',
      'Sugali / Lambadi / Banjara',
      'Thoti',
      'Valmiki (Agency)',
      'Yanadi',
      'Yerukula',
      'Other Sub-Caste'
    ],
    'Other': [
      'Other Sub-Caste'
    ]
  }
};
