export interface LocationData {
  states: string[];
  districts: Record<string, string[]>;
  mandals: Record<string, string[]>;
  villages: Record<string, string[]>;
}

export const AP_LOCATIONS: LocationData = {
  states: ['Andhra Pradesh', 'Telangana', 'Odisha', 'Other'],
  districts: {
    'Andhra Pradesh': [
      'Srikakulam',
      'Vizianagaram',
      'Visakhapatnam',
      'Anakapalli',
      'Parvathipuram Manyam',
      'Alluri Sitharama Raju',
      'Kakinada',
      'East Godavari',
      'Dr. B.R. Ambedkar Konaseema',
      'West Godavari',
      'Eluru',
      'Krishna',
      'NTR',
      'Guntur',
      'Bapatla',
      'Palnadu',
      'Prakasam',
      'SPS Nellore',
      'Kurnool',
      'Nandyal',
      'Ananthapuramu',
      'Sri Sathya Sai',
      'YSR Kadapa',
      'Annamayya',
      'Chittoor',
      'Tirupati'
    ],
    'Telangana': [
      'Hyderabad',
      'Rangareddy',
      'Medchal-Malkajgiri',
      'Warangal',
      'Khammam',
      'Nizamabad',
      'Karimnagar',
      'Nalgonda',
      'Mahabubnagar'
    ],
    'Odisha': [
      'Ganjam',
      'Gajapati',
      'Rayagada',
      'Koraput',
      'Khordha (Bhubaneswar)'
    ],
    'Other': ['Other District']
  },
  mandals: {
    'Srikakulam': [
      'Narasannapeta',
      'Polaki',
      'Jalumuru',
      'Kotabommali',
      'Gara',
      'Etcherla',
      'Ponduru',
      'Sarubujjili',
      'Srikakulam (Rural)',
      'Srikakulam (Urban)',
      'Amadalavalasa',
      'Tekkali',
      'Nandigam',
      'Ranasthalam',
      'Laveru',
      'Burja',
      'Santhabommali',
      'Palasa - Kasibugga',
      'Sompeta',
      'Mandasa',
      'Itchapuram',
      'Kaviti',
      'Kanchili',
      'Saravakota',
      'Pathapatnam',
      'Meliaputti',
      'Hiramandalam',
      'Kotturu',
      'Rajam',
      'G.Sigadam',
      'L.N. Peta',
      'Vangara',
      'Regidi Amadalavalasa',
      'Santhakaviti',
      'Vajrapukothuru',
      'Palakonda',
      'Seethampeta',
      'Bhamini',
      'Veeraghattam',
      'Other Mandal'
    ],
    'Vizianagaram': [
      'Vizianagaram',
      'Bhogapuram',
      'Cheepurupalli',
      'Denkada',
      'Gajapathinagaram',
      'Garividi',
      'Gurla',
      'Jami',
      'Kothavalasa',
      'Lakkavarapukota',
      'Nellimarla',
      'Pusapatirega',
      'Srungavarapukota',
      'Vepada',
      'Other Mandal'
    ],
    'Visakhapatnam': [
      'Visakhapatnam (Urban)',
      'Gajuwaka',
      'Anandapuram',
      'Bheemunipatnam',
      'Padmanabham',
      'Pendurthi',
      'Maharanipeta',
      'Seethammadhara',
      'Other Mandal'
    ]
  },
  villages: {
    'Narasannapeta': [
      'Narasannapeta 1 (Ward 1)',
      'Narasannapeta 2 (Ward 2)',
      'Narasannapeta 3 (Ward 3)',
      'Narasannapeta 4 (Ward 4)',
      'Borigivalasa',
      'Chennapuram',
      'Chikkalavalasa',
      'Chodavaram',
      'Gopalapenta',
      'Lukalam',
      'Madapam',
      'Makivalasa',
      'Nadagam',
      'Ravulavalasa',
      'Satyavaram R',
      'Tamarapalli',
      'Telagavalasa',
      'Urlam',
      'Yarabadu',
      'Komarthi',
      'Karavanja',
      'Jamachakram',
      'Borubhadra',
      'Thamminaidupeta',
      'Gorripadu',
      'Tilaru',
      'Other Village/Sachivalayam'
    ],
    'Polaki': [
      'Polaki 1',
      'Polaki 2',
      'Ampalam',
      'Belamara Polavalasa',
      'Boddam',
      'Challayyavalasa',
      'Cheedivalasa',
      'Gollalavalasa',
      'Jaduru',
      'Koduru',
      'Kusumpolavalasa',
      'Mabagam',
      'Priyagraharam',
      'Rahimanpuram',
      'Talasamudram',
      'Urjam',
      'Susaram',
      'Dola',
      'Gujjuvada',
      'Ampolu',
      'Mulasavalapuram',
      'Temburu',
      'Chintada',
      'Other Village/Sachivalayam'
    ],
    'Jalumuru': [
      'Jalumuru',
      'Akkurada',
      'Allada',
      'Andhavaram',
      'Challavanipeta',
      'Gotivada',
      'Gudivada',
      'Makannapeta',
      'Nagarikatakam',
      'Pagodu',
      'Parlam',
      'Peddadugam',
      'Rana',
      'Ravipadu',
      'Srimukhalingam',
      'Syrigam',
      'Talatariya',
      'Tekkalipadu',
      'Timadam',
      'Venkatapuram',
      'Yelamanchili',
      'Karada',
      'Kothapeta',
      'Lingalapadu',
      'Other Village/Sachivalayam'
    ],
    'Kotabommali': [
      'Kotabommali 1',
      'Kotabommali 2',
      'Cheepuralapadu',
      'Chinnasana',
      'Chittivalasa',
      'Dantha',
      'Harichandrapuram',
      'Jarjangi 1',
      'Jarjangi 2',
      'Kistupuram',
      'Kothapalli',
      'Kothapeta 1',
      'Kothapeta 2',
      'Kurudu',
      'Lakhimdiddi 1',
      'Lakhimdiddi 2',
      'Masahebpeta',
      'Komanapalli',
      'Pakivalasa',
      'Nimzada',
      'Thilavada',
      'Borubhadra',
      'Yadavalasa',
      'Peddasana',
      'Gunduvillipeta',
      'Other Village/Sachivalayam'
    ],
    'Gara': [
      'Gara 1',
      'Gara 2',
      'Srikurmam 1',
      'Srikurmam 2',
      'Kalingapatnam 1',
      'Kalingapatnam 2',
      'Salihundam',
      'Vatsavalasa',
      'Ramachandrapuram',
      'Thonangi',
      'Ampolu',
      'Nizampatnam',
      'Arasavilli Road',
      'Calapatnam',
      'Ganti',
      'Jhadupeta',
      'Kompalli',
      'Madapam Beach',
      'Pallepeta',
      'Peddapadu Gara',
      'Shalivahanam',
      'Srikurmam Rural',
      'Vaidyula Peta',
      'Vamaravilli',
      'Buravilli',
      'Singupuram Gara',
      'Other Village/Sachivalayam'
    ],
    'Etcherla': [
      'Etcherla 1',
      'Etcherla 2',
      'Chilakapalem 1',
      'Chilakapalem 2',
      'Ponnada 1',
      'Ponnada 2',
      'Kongaram',
      'Fareedpeta',
      'D.Matchilesam 1',
      'D.Matchilesam 2',
      'Bonthalakoduru',
      'Kothapeta Etcherla',
      'Kusulavada',
      'Allinagaram',
      'Budumuru',
      'Thotapalem Etcherla',
      'Jarjam',
      'Kaviti Etcherla',
      'Laxmipuram',
      'Nandigam Etcherla',
      'Pathivada',
      'Peddapadu Rural',
      'Rallapalli',
      'Subhadrapuram',
      'Tamminaidupeta',
      'Keshava Rao Peta',
      'Bhyravapeta',
      'Navodaya Camp',
      'Other Village/Sachivalayam'
    ],
    'Ponduru': [
      'Ponduru 1',
      'Ponduru 2',
      'Ponduru 3',
      'Rapaka 1',
      'Rapaka 2',
      'Dusi 1',
      'Dusi 2',
      'Gorinta',
      'Dallavalasa',
      'Thotada',
      'Thandemvalasa',
      'Voni',
      'Kinthali',
      'Malakam',
      'Lolugu 1',
      'Lolugu 2',
      'Bammidi',
      'Gajulagollavalsa',
      'Gudivada Ponduru',
      'Kanimetta',
      'Kotthapalli Ponduru',
      'Madhavam',
      'Nandivada',
      'Penubarthi',
      'Pillalavalasa',
      'Singupuram Ponduru',
      'Tholapi',
      'Venkataraopeta',
      'Other Village/Sachivalayam'
    ],
    'Sarubujjili': [
      'Sarubujjili',
      'Purushottapuram',
      'Kusalapuram',
      'Shalantri',
      'Rettada',
      'Palavalasa',
      'Thotavada',
      'Amritalinganagaram',
      'Boddavalasa',
      'Chinnakusalapuram',
      'Danthanapeta',
      'Gudivada Sarubujjili',
      'Komanapalli',
      'Madanapuram',
      'Mocharla',
      'Peddapalavalasa',
      'Ravada',
      'Yerravaram',
      'Other Village/Sachivalayam'
    ],
    'Srikakulam (Rural)': [
      'Singupuram 1',
      'Singupuram 2',
      'Peddapadu 1',
      'Peddapadu 2',
      'Pathasrikakulam',
      'Chapuram Rural',
      'Voppangi',
      'Kallepalli',
      'Thotapalem',
      'Karvanjivalasa',
      'Gulumuru',
      'Kusulavada Rural',
      'Ragolu 1',
      'Ragolu 2',
      'Thotada Rural',
      'Vomaravilli',
      'Alikam Rural',
      'Bhyri',
      'Chinnapadu',
      'Dandulaxmipuram',
      'Gara Road',
      'Kalingapatnam Road',
      'Khazipeta',
      'Musalinaidupeta',
      'Ponnam',
      'Other Village/Sachivalayam'
    ],
    'Srikakulam (Urban)': [
      'Ward 1 (Arasavalli Main)',
      'Ward 2 (Arasavalli Temple)',
      'Ward 3 (Balaga North)',
      'Ward 4 (Balaga South)',
      'Ward 5 (Gujarathipeta East)',
      'Ward 6 (Gujarathipeta West)',
      'Ward 7 (Chapuram)',
      'Ward 8 (Killi Veedhi)',
      'Ward 9 (Peddapadu)',
      'Ward 10 (Fazulbegpeta)',
      'Ward 11 (Patrunivalasa)',
      'Ward 12 (Santhi Nagar)',
      'Ward 13 (Illisipuram)',
      'Ward 14 (P.S.R. Colony)',
      'Ward 15 (Seven Hills)',
      'Ward 16 (Housing Board)',
      'Ward 17 (Visakha Colony)',
      'Ward 18 (Simhadri Nagar)',
      'Ward 19 (Old Bus Stand)',
      'Ward 20 (Palakonda Road)',
      'Ward 21 (Rythu Bazaar Area)',
      'Ward 22 (Collectorate Area)',
      'Ward 23 (Court Complex Area)',
      'Ward 24 (RIMS Area)',
      'Ward 25 (Day & Night Junction)',
      'Ward 26 (GT Road)',
      'Ward 27 (Seven Road Junction)',
      'Ward 28 (Women\'s College Road)',
      'Ward 29 (Navabharat Junction)',
      'Ward 30 (Suryanarayana Colony)',
      'Ward 31 (Bankers Colony)',
      'Ward 32 (Arts College Road)',
      'Ward 33 (Nagavali River View)',
      'Ward 34 (Indira Nagar)',
      'Ward 35 (Srinivasa Nagar)',
      'Ward 36 (Ameen Sahib Peta)',
      'Other Village/Sachivalayam'
    ],
    'Amadalavalasa': [
      'Amadalavalasa Ward 1',
      'Amadalavalasa Ward 2',
      'Amadalavalasa Ward 3',
      'Amadalavalasa Ward 4',
      'Amadalavalasa Ward 5',
      'Amadalavalasa Ward 6',
      'Amadalavalasa Ward 7',
      'Amadalavalasa Ward 8',
      'Alikam',
      'Gudivada Amadalavalasa',
      'Thogaram 1',
      'Thogaram 2',
      'Kothavalasa',
      'Belamam',
      'Calingapatnam Amadalavalasa',
      'Chinakollivalasa',
      'Dusi Amadalavalasa',
      'Jonnavalasa',
      'Katari Tekkali',
      'Mandavakuriti',
      'Modugulapeta',
      'Nannevalasa',
      'Parlam Amadalavalasa',
      'Other Village/Sachivalayam'
    ],
    'Tekkali': [
      'Tekkali Ward 1',
      'Tekkali Ward 2',
      'Tekkali Ward 3',
      'Tekkali Ward 4',
      'Tekkali Ward 5',
      'Akkayyavalasa',
      'Raghunadhapuram 1',
      'Raghunadhapuram 2',
      'Temburu',
      'Polaki Tekkali',
      'Lingalapadu',
      'Seeta Nagar',
      'Ravivalasa',
      'Gangaram',
      'Bhagirathipuram',
      'Chintalapeta',
      'Nandigam Road',
      'Kotturu Tekkali',
      'Bhairavapalli',
      'Kottapalli',
      'Pathatekkali',
      'Peddasrirampuram',
      'Ravivalasa 2',
      'Santhoshapuram',
      'Telukunchi',
      'Other Village/Sachivalayam'
    ],
    'Ranasthalam': [
      'Ranasthalam 1',
      'Ranasthalam 2',
      'Pydibhimavaram 1',
      'Pydibhimavaram 2',
      'Allivalasa',
      'Derasam',
      'Pisini 1',
      'Pisini 2',
      'J.R.Puram 1',
      'J.R.Puram 2',
      'Kovvada 1',
      'Kovvada 2',
      'Pathivada',
      'Kammasigadam',
      'Mentada',
      'Chinnaraopeta',
      'Gosani',
      'Jeerupalem',
      'Kosta',
      'Maruvada',
      'Nelivada',
      'Pannada',
      'Ramachandrapuram',
      'Teppalavalasa',
      'Velagada',
      'Venkatarayapuram',
      'Yerramsettivalasa',
      'N.G.Puram',
      'Other Village/Sachivalayam'
    ],
    'Laveru': [
      'Laveru 1',
      'Laveru 2',
      'Adapaka',
      'Bejjipuram',
      'Budathavalasa',
      'Kothakota',
      'Murapaka 1',
      'Murapaka 2',
      'Subhadrapuram',
      'Venkatapuram Laveru',
      'Bayyavaram',
      'Chinnaraopeta Laveru',
      'Garikapadu',
      'Gudem',
      'Kaguvada',
      'Keshavaraopeta',
      'Kumaram',
      'Nagampalli',
      'Peddalingalavalasa',
      'Pothayyavalasa',
      'Rangarayapuram',
      'Santha Lakshmipuram',
      'Tamminaidupeta',
      'Other Village/Sachivalayam'
    ],
    'Burja': [
      'Burja 1',
      'Burja 2',
      'Labbavani Peta 1',
      'Labbavani Peta 2',
      'Kollivalasa',
      'Mamidivalasa',
      'Thotada Burja',
      'Palavalasa Burja',
      'Ananthapuram',
      'Allena',
      'Boddam Burja',
      'Chinna Laxmipuram',
      'Gulumuru Burja',
      'Jagannadhapuram',
      'Madanapuram Burja',
      'Peddapadu Burja',
      'Singannavalasa',
      'Sundarapuram',
      'Venkampeta',
      'Yadiki',
      'Other Village/Sachivalayam'
    ],
    'Santhabommali': [
      'Santhabommali 1',
      'Santhabommali 2',
      'Govindapuram',
      'Megavaram',
      'Palathalagam 1',
      'Palathalagam 2',
      'Borubhadra Santhabommali',
      'Bhavanapadu 1',
      'Bhavanapadu 2',
      'Maruvada',
      'Dandugopalapuram',
      'Chinna Tungam',
      'Diguva Kaspapeta',
      'Haddubangy',
      'Kotapadu',
      'Modugulapalli',
      'Peddatungam',
      'Polavaram',
      'Rajapuram',
      'Rudrakota',
      'Ukkambadra',
      'Vadditandra',
      'Other Village/Sachivalayam'
    ],
    'Palasa - Kasibugga': [
      'Palasa Ward 1',
      'Palasa Ward 2',
      'Palasa Ward 3',
      'Palasa Ward 4',
      'Palasa Ward 5',
      'Palasa Ward 6',
      'Kasibugga Ward 1',
      'Kasibugga Ward 2',
      'Kasibugga Ward 3',
      'Kasibugga Ward 4',
      'Kasibugga Ward 5',
      'Chinnabadam',
      'Peddabadam',
      'Brahmanatarla',
      'Garudabhadra',
      'Rentikota',
      'Mogilipadu',
      'Ramakrishnapuram',
      'Tarangapuram',
      'Allukola',
      'Badagandi',
      'Gudivada Palasa',
      'Kedaripuram',
      'Laxmipuram Palasa',
      'Mandoor',
      'Nagiripenta',
      'Padmapuram',
      'Rambhadrapuram',
      'Sunnadevi',
      'Tekkalipatnam',
      'Udayapuram',
      'Other Village/Sachivalayam'
    ],
    'Sompeta': [
      'Sompeta Ward 1',
      'Sompeta Ward 2',
      'Sompeta Ward 3',
      'Sompeta Ward 4',
      'Baruva 1',
      'Baruva 2',
      'Sasanam',
      'Korlam',
      'Zinkibhadra',
      'Mandapalli',
      'Benkili',
      'Rajam Sompeta',
      'Rushikudda',
      'Isakalapalem',
      'Palavalasa Sompeta',
      'Besiputtuga',
      'Chinna Bhyripuram',
      'Dondapadu',
      'Gollagandi',
      'Kattumuru',
      'Mamidi Palli',
      'Penta',
      'Rampalli',
      'Tallabadra',
      'Yadupuram',
      'Other Village/Sachivalayam'
    ],
    'Mandasa': [
      'Mandasa 1',
      'Mandasa 2',
      'Haripuram 1',
      'Haripuram 2',
      'Bhyripuram',
      'Pitasimi',
      'Somarajupeta',
      'Subhadrapuram',
      'Cheepi',
      'Budambo',
      'Dokulapadu Mandasa',
      'Kuntikota',
      'Bahadapalli',
      'Bhogapuram Mandasa',
      'Chinna Lamba',
      'Devunalthada',
      'Gollagandi',
      'Kondatemburu',
      'Laxmipuram Mandasa',
      'Mandarada',
      'Narayanapuram',
      'Peddalamba',
      'Ratnamani',
      'Sabbi Palli',
      'Sariyapalli',
      'Vombali',
      'Other Village/Sachivalayam'
    ],
    'Itchapuram': [
      'Itchapuram Ward 1',
      'Itchapuram Ward 2',
      'Itchapuram Ward 3',
      'Itchapuram Ward 4',
      'Itchapuram Ward 5',
      'Itchapuram Ward 6',
      'Kavisiti',
      'Bellupada Itchapuram',
      'Edupuram 1',
      'Edupuram 2',
      'Loddaputti',
      'Birlangi',
      'Tulu',
      'Dharmapuram',
      'Masakhapuram',
      'Arakabadra',
      'Baligam',
      'Buradapalli',
      'Haripuram Itchapuram',
      'Kesupuram',
      'Kotthagumpa',
      'Lalapeta',
      'Mandarada Itchapuram',
      'Pattupuram',
      'Solabandha',
      'Other Village/Sachivalayam'
    ],
    'Kaviti': [
      'Kaviti 1',
      'Kaviti 2',
      'Rajapuram Kaviti',
      'Jagati 1',
      'Jagati 2',
      'Kapasakuddi',
      'Bellupada Kaviti',
      'Borivanka 1',
      'Borivanka 2',
      'Varaka',
      'Nelavanka',
      'Silagam',
      'Balliputtuga',
      'Chintamani',
      'Duggapuvalasa',
      'Gondevalasa',
      'Kancharlapalli',
      'Manikyapuram',
      'Mutturu',
      'Puttiyadurgam',
      'Siddantham',
      'Vaidyulapeta',
      'Other Village/Sachivalayam'
    ],
    'Kanchili': [
      'Kanchili 1',
      'Kanchili 2',
      'Makarampuram',
      'Sasanam Kanchili',
      'Jadupudi 1',
      'Jadupudi 2',
      'Talatampara',
      'Mondrajupeta',
      'Kumbharipeta',
      'Baligam Kanchili',
      'Boddabada',
      'Chinnasrirampuram',
      'Gokarnapuram',
      'Kanimetta Kanchili',
      'Kesarapada',
      'Kothuru Kanchili',
      'Matam',
      'Peddasrirampuram Kanchili',
      'Samantapalli',
      'Sariapalli',
      'Sunnadevi Kanchili',
      'Talapada',
      'Other Village/Sachivalayam'
    ],
    'Saravakota': [
      'Saravakota',
      'Aludu',
      'Budathanapalli',
      'Chinnagollapalli',
      'Gujjumani',
      'Komanapalli Saravakota',
      'Pathakota',
      'Gollapalli',
      'Gorripadu Saravakota',
      'Gummapadu',
      'Jadupalli',
      'Kottakota',
      'Maddivalasa',
      'Mettavalasa',
      'Palavalasa Saravakota',
      'Ponnada Saravakota',
      'Savitripuram',
      'Singupuram Saravakota',
      'Thotada Saravakota',
      'Vombali Saravakota',
      'Other Village/Sachivalayam'
    ],
    'Pathapatnam': [
      'Pathapatnam Ward 1',
      'Pathapatnam Ward 2',
      'Pathapatnam Ward 3',
      'A.S.Peta',
      'Korasanda',
      'Marripadu',
      'Seethapuram',
      'Tekkalipatnam Pathapatnam',
      'Bakshipeta',
      'Chinnaseedhi',
      'Diguvamandasa',
      'Gangavaram',
      'Gudivada Pathapatnam',
      'Kandisa',
      'Kavallipeta',
      'Musalipeta',
      'Peddaseedhi',
      'Rambhadrapuram Pathapatnam',
      'Siddhapuram',
      'Talavaram',
      'Temburu Pathapatnam',
      'Veeranarayana',
      'Other Village/Sachivalayam'
    ],
    'Meliaputti': [
      'Meliaputti 1',
      'Meliaputti 2',
      'Chapara 1',
      'Chapara 2',
      'Marripadu Meliaputti',
      'Patrapalli',
      'Peddapadmapuram',
      'Sundarada',
      'Borigipeta',
      'Chinnapadmapuram',
      'Dinnabandha',
      'Gokhalapuram',
      'Jhadupalli',
      'Kotturu Meliaputti',
      'Mamidipalli Meliaputti',
      'Mohanapuram',
      'Peddasari',
      'Ramakrishnapuram Meliaputti',
      'Sunnapalli',
      'Talamala',
      'Other Village/Sachivalayam'
    ],
    'Hiramandalam': [
      'Hiramandalam 1',
      'Hiramandalam 2',
      'Bagiradhapuram',
      'Gottipalli',
      'Pedduru',
      'Subalaya',
      'Tungathampara',
      'Ambatavalsan',
      'Chinna Kollivalasa Hiramandalam',
      'Gulumuru Hiramandalam',
      'Kollivalasa Hiramandalam',
      'Kondada',
      'Laxminarasimhapuram',
      'Mamidivalasa Hiramandalam',
      'Pilligollavalasa',
      'Santhanarasimhapuram',
      'Sumitrapuram',
      'Vajrachandrapuram',
      'Vemulavada',
      'Other Village/Sachivalayam'
    ],
    'Kotturu': [
      'Kotturu 1',
      'Kotturu 2',
      'Althi',
      'Bhamini Road',
      'Kadumu',
      'Mathala',
      'Nivagam',
      'Parapuram',
      'Badabanda',
      'Chinnaguruvulu',
      'Dombaguda',
      'Gurandi',
      'Kotturu Rural',
      'Maha Singi',
      'Marikavalasa',
      'Peddaguruvulu',
      'Rayagada Kotturu',
      'Seethampeta Road',
      'Subhadrapuram Kotturu',
      'Venkampeta Kotturu',
      'Other Village/Sachivalayam'
    ],
    'Rajam': [
      'Rajam Ward 1',
      'Rajam Ward 2',
      'Rajam Ward 3',
      'Rajam Ward 4',
      'Rajam Ward 5',
      'Rajam Ward 6',
      'Boddam Rajam',
      'Kothavalasa Rajam',
      'Marrivalasa',
      'Pogiri 1',
      'Pogiri 2',
      'Vangara Road',
      'Antakapalli',
      'Chinna Laxmipuram Rajam',
      'Gadelavalasa',
      'Gollavalasa Rajam',
      'Kancharam',
      'Kotthapeta Rajam',
      'Muddada',
      'Nandabalaga',
      'Peddapenki',
      'Radham',
      'Santhavuriti Rajam',
      'Saradhi',
      'Vaddi Valasa',
      'Other Village/Sachivalayam'
    ],
    'G.Sigadam': [
      'G.Sigadam',
      'Geddapuvalasa',
      'Jagannadhapuram Sigadam',
      'Madhupuram',
      'Santhavuriti',
      'Adapaka Sigadam',
      'Bavanapadu Sigadam',
      'Chinnaraopeta Sigadam',
      'Devarapalli',
      'Gollapalli Sigadam',
      'Kalyanipeta',
      'Kothapalli Sigadam',
      'Metta Valasa Sigadam',
      'Nandivada Sigadam',
      'Penta Sigadam',
      'Ramadasupeta',
      'Singupuram Sigadam',
      'Thotapalem Sigadam',
      'Venkataraopeta Sigadam',
      'Yaragam Sigadam',
      'Other Village/Sachivalayam'
    ],
    'L.N. Peta': [
      'L.N. Peta',
      'Karadavalasa',
      'Mamidivalasa LN Peta',
      'Pothampeta',
      'Venkampeta LN Peta',
      'Balarampuram',
      'Chinnaguruvulu LN Peta',
      'Dabbapadupeta',
      'Gollapadu',
      'Jhadupalli LN Peta',
      'Kallepalli LN Peta',
      'Koturuguda',
      'Muddadapeta',
      'Peddaguruvulu LN Peta',
      'Savitripuram LN Peta',
      'Singupuram LN Peta',
      'Thotada LN Peta',
      'Yelamanchili LN Peta',
      'Other Village/Sachivalayam'
    ],
    'Vangara': [
      'Vangara',
      'Madduvalasa',
      'Kothavalasa Vangara',
      'Sangam',
      'Sitarampuram',
      'Bhagiradhapuram Vangara',
      'Chinnakollivalasa Vangara',
      'Devunikanithi',
      'Gopinadhapuram',
      'Koppara',
      'Laxmipuram Vangara',
      'Mamidivalasa Vangara',
      'Narayana Puram',
      'Pathakota Vangara',
      'Rambhadrapuram Vangara',
      'Sivvam',
      'Thotapalli',
      'Voni Vangara',
      'Other Village/Sachivalayam'
    ],
    'Regidi Amadalavalasa': [
      'Regidi',
      'Amadalavalasa Regidi',
      'Sankili',
      'Ungarada',
      'Kandisa Regidi',
      'Akkayyavalasa Regidi',
      'Baligam Regidi',
      'Chinnayyapeta',
      'Devunigumpa',
      'Gollavalasa Regidi',
      'Kaguvada Regidi',
      'Katamani',
      'Kothavalasa Regidi',
      'Muddadapeta Regidi',
      'Nagampalli Regidi',
      'Peddapadmapuram Regidi',
      'Ramayyapeta',
      'Samakhandi',
      'Seetharampuram Regidi',
      'Venkampeta Regidi',
      'Other Village/Sachivalayam'
    ],
    'Santhakaviti': [
      'Santhakaviti',
      'Billalavalasa',
      'Mandarada',
      'Talada',
      'Appapuram',
      'Boddavalasa Santhakaviti',
      'Chittivalasa Santhakaviti',
      'Garimellapeta',
      'Gokarnapuram Santhakaviti',
      'Honjaram',
      'Kancharam Santhakaviti',
      'Kavitam',
      'Makarampuram Santhakaviti',
      'Mandavakuriti Santhakaviti',
      'Muddada Santhakaviti',
      'Peddapadu Santhakaviti',
      'Ramannapeta',
      'Siri Puram',
      'Thumbali',
      'Vani Peta',
      'Other Village/Sachivalayam'
    ],
    'Vajrapukothuru': [
      'Vajrapukothuru',
      'Baruvapeta',
      'Dokulapadu Vajrapukothuru',
      'Garudabhadra Vajrapukothuru',
      'Pallivada',
      'Balarampuram Vajrapu',
      'Bhyripuram Vajrapu',
      'Chinabadam Vajrapu',
      'Devunalthada Vajrapu',
      'Gobburu',
      'Kondatemburu Vajrapu',
      'Kotthapalli Vajrapu',
      'Mamidipalli Vajrapu',
      'Manikyapuram Vajrapu',
      'Pathatekkali Road',
      'Peddabadam Vajrapu',
      'Pundi 1',
      'Pundi 2',
      'Ramachandrapuram Vajrapu',
      'Rishikudda Vajrapu',
      'Ukkambadra Vajrapu',
      'Vombali Vajrapu',
      'Other Village/Sachivalayam'
    ],
    'Palakonda': [
      'Palakonda Ward 1',
      'Palakonda Ward 2',
      'Palakonda Ward 3',
      'Palakonda Ward 4',
      'Palakonda Ward 5',
      'Palakonda Ward 6',
      'Annavaram Palakonda',
      'Bhyripuram Palakonda',
      'Chinnaguruvulu Palakonda',
      'Dolamada',
      'Gopalapuram',
      'Jhadupalli Palakonda',
      'Kanimetta Palakonda',
      'Kotadurga',
      'Lumburu',
      'Malliveedu',
      'Navagumpa',
      'Panukuvalasa',
      'Singannavalasa Palakonda',
      'Talada Palakonda',
      'Thumpallivalasa',
      'Vadigam',
      'Varthanapalli',
      'Veeranarayana Palakonda',
      'Other Village/Sachivalayam'
    ],
    'Seethampeta': [
      'Seethampeta',
      'Dombaguda',
      'Jatapu Colony',
      'Kaddagandi',
      'Kusumuru',
      'Malliveedu Seethampeta',
      'Mandaguda',
      'Maredumilli Seethampeta',
      'Peddaguda',
      'Pedduru Seethampeta',
      'Pilligollavalasa Seethampeta',
      'Polla',
      'Raiduguda',
      'Sambham',
      'Sobba',
      'Sunnapalli Seethampeta',
      'Talada Seethampeta',
      'Thitukupayi',
      'Valagadda',
      'Vompalli',
      'Other Village/Sachivalayam'
    ],
    'Bhamini': [
      'Bhamini',
      'Battili',
      'Belamara',
      'Chinnadiman',
      'Dimmidijola',
      'Gollagandi Bhamini',
      'Kaguvada Bhamini',
      'Kosali',
      'Kotthuru Road',
      'Liviri',
      'Manchalapeta',
      'Muddadapeta Bhamini',
      'Naguru',
      'Peddadiman',
      'Peram',
      'Soliveedu',
      'Talada Bhamini',
      'Valagadda Bhamini',
      'Other Village/Sachivalayam'
    ],
    'Veeraghattam': [
      'Veeraghattam 1',
      'Veeraghattam 2',
      'Chinnagollapalli Veeraghattam',
      'Chittipudivalasa',
      'Dasari Peta',
      'Gadabavalasa',
      'Hussainapuram',
      'Kambara',
      'Kimmi',
      'Kotadurga Veeraghattam',
      'Kumbhidikota',
      'Nadukuru',
      'Neelanagaram',
      'Palavalasa Veeraghattam',
      'Panukuvalasa Veeraghattam',
      'Regulapadu',
      'Santha Seetharampuram',
      'Thotapalli Veeraghattam',
      'Tudumu',
      'Vanduva',
      'Vikrampuram',
      'Yedulavalasa',
      'Other Village/Sachivalayam'
    ],
    'Nandigam': [
      'Nandigam 1',
      'Nandigam 2',
      'Dimmidijola',
      'Kottagraharam',
      'Lakhidasupuram',
      'Nowgam',
      'Peddabanapuram',
      'Peddalavunipalli',
      'Peddatamarapalli',
      'Radhajanaboddapadu',
      'Sivarampuram',
      'Sylada',
      'Bejjipalli',
      'Badagam',
      'Deenabandupuram',
      'Karlapudi',
      'Mondraivalasa',
      'Narendrapuram',
      'Rampuram',
      'Anandapuram',
      'Gollavooru',
      'Subhadrapuram Nandigam',
      'Kaviti Nandigam',
      'Other Village/Sachivalayam'
    ],
    'Vizianagaram': [
      'Ward 1 (Contonment)',
      'Ward 2 (Phoolbaugh)',
      'Ward 3 (Mayuri Junction)',
      'Ward 4 (RTC Complex)',
      'Ward 5 (Collectorate)',
      'Ward 6 (Fort Area)',
      'Ward 7 (Kothapeta)',
      'Ward 8 (Balaji Nagar)',
      'Ward 9 (Ring Road)',
      'Other Village/Sachivalayam'
    ],
    'Bhogapuram': [
      'Bhogapuram',
      'Munjeru',
      'Polipalli',
      'Savara Palli',
      'Tagarapuvalasa Border',
      'Other Village/Sachivalayam'
    ],
    'Cheepurupalli': [
      'Cheepurupalli Ward 1',
      'Cheepurupalli Ward 2',
      'Garividi Road',
      'Metpalli',
      'Karlam',
      'Other Village/Sachivalayam'
    ],
    'Visakhapatnam (Urban)': [
      'Ward 1 (Madhurawada)',
      'Ward 2 (Yendada)',
      'Ward 3 (MVP Colony)',
      'Ward 4 (Siripuram)',
      'Ward 5 (Dwaraka Nagar)',
      'Ward 6 (Daba Gardens)',
      'Ward 7 (Jagadamba)',
      'Ward 8 (Gajuwaka)',
      'Ward 9 (Pendurthi)',
      'Ward 10 (Gopalapatnam)',
      'Other Village/Sachivalayam'
    ]
  }
};
